[package]
name = "postgres_rust"
version = "0.0.1"
edition = "2021"

[lib]
name = "postgres_rust"
crate-type = ["staticlib"]      # Creates dynamic lib

[dependencies]
libc = "*"

[features]
default = []
pg_rewind = []
